import { Project } from "./project";

export const categories = {
  NFT: "nft",
  INFRASTRUCTURE: "infrastructure",
  DEFI: "defi",
  MARKETPLACE: "marketplace",
  BRIDGE: "bridge",
  DEX : "dex",
  HACKATHON : "hackathon"
 
};
export const allProjects: Project[] = [
  {
    title: "Social Swap",
    url: "https://www.socialswap.io/",
    description: "Diffusion is an Automated Market Maker (AMM) protocol and liquidity pool designed for efficient trading between crypto-assets. The trading activity on Diffusion captures fees as revenue for liquidity providers, resulting in a decentralized market and trading experience. ",
    image: "/diffusion.png",
    categories: [categories.DEX ],

  },
  {
    title: "Connext",
    url: "https://bridge.connext.network/",
    description: "Connext is an interoperability protocol that empowers developers to build fully expressive cross domain apps (xApps) with a strong focus on security.",
    image: "/connext.png",
    categories: [categories.BRIDGE],
  },
  {
    title: "JustLend",
    url: "https://app.justlend.org/#/home",
    description: "JustLend is a TRON-powered coin market protocol aimed at establishing fund pools whose interest rates are determined by an algorithm based on the supply and demand of TRON assets..",
    image: "/justlend.jpg",
    categories: [categories.DEFI],
  },
  {
    title: "JustStables",
    url: "https://juststable.tronscan.org/#/login",
    description: "JustStable is a decentralized finance system of USDJ stablecoin for everyone, anywhere, anytime.",
    image: "/juststables.jpg",
    categories: [categories.DEX],
  },
  {
    title: "SUN",
    url: "https://sun.io/",
    description: "First integrated platform for stablecoin swap, stake-mining, and self-governance on TRON",
    image: "/Sun.jpg",
    categories: [categories.DEX],
  },
  {
    title: "SocialSwap",
    url: "https://www.socialswap.io/",
    description: "Socialswap is a decentralized exchange on tron blockchain.",
    image: "/socialswap.jpg",
    categories: [categories.DEX],
  },
  {
    title: "UniFi",
    url: "https://unifiprotocol.com/",
    description: "Unifi Protocol is a group of non-custodial, interoperable smart contracts linking multiple blockchains together into one large DeFi marketplace..",
    image: "/unifi.jpg",
    categories: [categories.DEX],
  },
  {
    title: "JustMoney",
    url: "https://about.just.money/",
    description: "An ecosystem for the next generation of decentralized applications to power Web3 and DeFi.",
    image: "/justmoney.jpg",
    categories: [categories.DEX],
  },
  {
    title: "OneSwap",
    url: "https://www.oneswap.net/",
    description: "A fully decentralized exchange protocol on Smart Contract, with permission-free token listing and automated market making.",
    image: "/oneswap.jpg",
    categories: [categories.DEX],
  },
  {
    title: "LuminousFinance",
    url: "https://luminous.finance/",
    description: "Lumi is a token based on the Tron blockchain. Lumi was created as a popular and utility token for the Luminous ecosystem.",
    image: "/luminusfinance.jpg",
    categories: [categories.DEX],
  },
  {
    title: "MetaBid",
    url: "https://devpost.com/software/metabid",
    description: "Metabid is a platform that allows people to auction and sell their second-hand cars or valuables, similar to real life ones. At the same time, people have the opportunity to open a store and sell their products with METABLOK tokens in the metaverse environment.",
    image: "/metabid.png",
    categories: [categories.DEFI],
  },
  {
    title: "BrúFinance",
    url: "https://devpost.com/software/bru-finance-ni18vt",
    description: "Brú Finance creates a bridged ecosystem of DeFi and CeFi through its integrated custodian-based real-world asset tokenization and decentralised lending solution. This helps in channelling the high yield-seeking capital from the developed world to the unbanked and the underbanked in emerging markets through an open, borderless and bankless system of finance secured by RWAs that reduces collection risk.",
    image: "/brufinance.png",
    categories: [categories.DEFI],
  },
  {
    title: "AlphaFinance",
    url: "https://devpost.com/software/bru-finance-ni18vt",
    description: "Alpha finance is a protocol and service that is a solution to the problems and needs of people in the DEFI world with a system that is secure and transparent, and also protects all consumer privacy.",
    image: "/alphafinance.png",
    categories: [categories.DEFI],
  },
  {
    title: "Coreburse",
    url: "https://devpost.com/software/coreburse-plf58b",
    description: "Coreburse is inspired by the practical value of Defi, which can perfectly apply blockchain technology to actual products, and people's pursuit of decentralization is becoming increasingly intense. To meet these needs, we created Coreburse.",
    image: "/coreburse.png",
    categories: [categories.DEFI],
  },
  {
    title: "HikaruFinance",
    url: "https://hikaru.fi",
    description: "Hikaru.fi is an automated portfolio manager that allows you to diversify your holdings smarter than ever.",
    image: "/hikaru.png",
    categories: [categories.DEFI],
  },
  {
    title: "Kattana",
    url: "https://app.kattana.io/pancakeswap/0xb5D108578Be3750209d1b3A8f45FFee8C5a75146",
    description: "Kattana.io Leading trading environment for DeFi. Entry point for global blockchain users. Kattana - is a trustable cross-chain trading terminal for DEXs and CEXs.",
    image: "/kattana.png",
    categories: [categories.DEFI,categories.HACKATHON,categories.DEX],
  },
  {
    title: "Calamus Finance",
    url: "https://calamus.finance/",
    description: "Your decentralized crypto streaming platform - Automate real-time salary, startup vesting or any transactions with enhanced security and transparency",
    image: "/calamusfinance.jpg",
    categories: [categories.DEFI,categories.HACKATHON],
  },
  {
    title: "MistTrack Analytics Platform",
    url: "https://misttrack.io/",
    description: "MistTrack analytics platform combines a number of SaaS systems designed specifically to target crypto money laundering. It's the one-stop destination for all of your investigating needs.",
    image: "/mistrack.png",
    categories: [categories.DEFI,categories.HACKATHON],
  },
  {
    title: "DAO Cake",
    url: "https://daocake.xyz/",
    description: "Making founder contributions easy. Bringing DAO tech to communities & startups.",
    image: "/daocake.png",
    categories: [categories.HACKATHON],
  },
  {
    title: "HolaChain",
    url: "https://tron.4thtech.io/",
    description: "Send, receive TRON dMails or exchange on-chain messages with no ads, no data mining & no tracking. HolaChain secures your E2EE communication and enables white-label SDKs for Web3 projects.",
    image: "/holachain.png",
    categories: [categories.HACKATHON],
  },
  {
    title: "Adshares ($ADS) in TronDAO Ecosystem!",
    url: "https://adshares.net/",
    description: "Adshares is an advertising Web3 protocol designed to provide blockchain-based ad software to ad tech industry. Metaverse & Game monetization allows community to monetize their virtual assets.",
    image: "/adshares.png",
    categories: [categories.NFT,categories.HACKATHON],
  },
  {
    title: "NRG & Community DAO",
    url: "https://tronnrg.com/",
    description: "Tron NRG is a Decentralized P2P energy rental service that allows users to save on Tron transaction fees by renting energy!",
    image: "/nrg.png",
    categories: [categories.HACKATHON],
  },
  {
    title: "CertiFi",
    url: "https://getcertifi.app/",
    description: "Blockchain based Credential Platform that lets institutions issue credentials and learners store, verify and share their credentials. Transcript Issuing cost for CertiFi ($0.56) << Conventional ($5+).",
    image: "/certifi.png",
    categories: [categories.HACKATHON],
  },
  {
    title: "Meson",
    url: "https://meson.fi/",
    description: "Meson introduces a next-gen cross-chain user experience on stablecoins - lightning-fast swap with unbelievably low cost among Ethereum, various high-performance public chains, and Layer 2's.",
    image: "/meson.png",
    categories: [categories.DEFI,categories.HACKATHON],
  },
  {
    title: "Dazzle Protocol",
    url: "https://testnet.dazzleprotocol.com/",
    description: "The easy first step into DeFi",
    image: "/dazzle.jpg",
    categories: [categories.DEFI,categories.HACKATHON],
  },
  {
    title: "Tron Security Dashcam",
    url: "https://github.com/BubblyOrca/Tron-Security-Dashcam",
    description: "The Tron Security Dashcam is a start-of-the-art collection of risk dashboards that monitors fishy activity that happens on-chain, & also notifies Tron Security experts about what's happening in Web3.",
    image: "/tron-security.png",
    categories: [categories.DEFI,categories.HACKATHON],
  },
  {
    title: "Wink Financial",
    url: "https://wink.financial/",
    description: "A Web3 Payroll & Treasury Management solution for web3 companies. Our mission is to empower DAOs, blockchain gaming studios & crypto companies to operate with agility and financial clarity.",
    image: "/wink.png",
    categories: [categories.DEFI,categories.HACKATHON],
  },
  {
    title: "Allbridge Core",
    url: "http://app.allbridge.io/",
    description: "Allbridge Core enables users to transfer native stablecoin liquidity between Tron and various EVM/non-EVM chains via decentralized cross-chain messaging protocols with an additional privacy layer.",
    image: "/allbridge.png",
    categories: [categories.HACKATHON],
  },
  {
    title: "Score Milk",
    url: "http://testing.scoremilk.com/games/1",
    description: "Score Milk is a platform built for the easy onboarding of games to Web 3.0. Our solutions include PvP patent pending bot deterrence, community/guild solutions, and a game dev SDK for easy onboarding.",
    image: "/scoremilk.png",
    categories: [categories.HACKATHON,categories.NFT],
  },
  {
    title: "Caloriecoin ",
    url: "https://github.com/caloriecoin",
    description: "E2E (Excercise To Earn) Smart Jump Rope Game CalorieCoin",
    image: "/caloriecoin.jpg",
    categories: [categories.NFT],
  },
  {
    title: "Cukies World",
    url: "https://cukies.world/",
    description: "Play-and-Earn multichain open world game with endless possibilities: explore the infinite archipelago, collect resources, build new tools, craft special gems, learn new skills, and enjoy!",
    image: "/cukies.png",
    categories: [categories.NFT],
  },
  {
    title: "TronVerse",
    url: "https://www.play.tronbullclub.com/",
    description: "TronVerse is an open world combat game built on the Unreal engine that utilizes the Tron Bull Club NFT collection. TronVerse will also provide a gaming rig to onboard other NFT collections.",
    image: "/tronverse.png",
    categories: [categories.NFT],
  },
  {
    title: "Rill",
    url: "https://github.com/Osamah/Rill",
    description: "Rill is a platform that will be used for e-sport tournaments. Players get rewarded instantly or after a game round has been concluded and distribute prizes depending on their achievements.",
    image: "/rill.png",
    categories: [categories.NFT],
  },
  {
    title: "TronNinjas",
    url: "https://tronninjas.com/",
    description: "TronNinjas is a NFT GameFi project on the Tron blockchain where you are able to play arcade games and earn our in-game token TronNinjas Token (TNT). The TNT token can be earned just by playing single-player games and in our bi-weekly tournaments with other NFT holders. We also have the Tronninjas store, where you can spend your TNT for upgrades.",
    image: "/tron-ninjas.png",
    categories: [categories.NFT],
  },
  {
    title: "Flynn",
    url: "https://docs.google.com/document/d/1WcFc_AQGInUT5knUJXOtu5lEuHHIugAn8Ui9EHFcM0c/edit?usp=sharing",
    description: "With Flynn tools, you can easily integrate your game or product into the Web3 world using familiar technologies and practices from the Web2 world. Create Web3 applications using a familiar stack!",
    image: "/flynn.png",
    categories: [categories.NFT],
  },
  {
    title: "GU3SS",
    url: "https://gu3ss.com/",
    description: "Decentralized betting app developed using smart contracts on TRON blockchain. Unrestricted, uncensorable, no KYC required, totally anonymous, you only need your TronLink wallet to play all you want.",
    image: "/gu3ss.jpg",
    categories: [categories.NFT],
  },
  {
    title: "Umbre",
    url: "https://umbre.xyz/",
    description: "Umbre is a one-stop service for all NFT creators. Umbre allows you to generate and deploy a TRC-721 contract on the Tron blockchain with any information and features. After the deployment, you can use mint button for integration, with which anyone can mint your NFT collection.",
    image: "/umbre.png",
    categories: [categories.NFT,categories.HACKATHON],
  },
  {
    title: "Apexgo",
    url: "https://www.apexgo.io/",
    description: "Apexgo is an NFT API solution focused on bringing NFT utility to enterprises, developers, and NFT enthusiasts. The objective is to integrate NFTs to everyone's day to day activities.",
    image: "/apexgo.png",
    categories: [categories.NFT,categories.HACKATHON],
  },
  {
    title: "Decentralease",
    url: "https://www.decentra.lease/",
    description: "Decentralease is a zero-collateral NFT renting and leasing platform built on the novel ERC-4907 standard.",
    image: "/decentralease.jpg",
    categories: [categories.NFT,categories.HACKATHON],
  },
  {
    title: "Helix Checkout",
    url: "https://hellohelix.app/",
    description: "Helix Checkout provides NFT creators a simple, fast, safe and secure way to sell NFTs on the TRON blockchain via credit card to consumers.",
    image: "/helix.png",
    categories: [categories.NFT,categories.HACKATHON],
  },
  {
    title: "NFTmall",
    url: "https://bttc.nftmall.io/",
    description: "NFT Infrastructure & Phygital NFT Commerce Provider for BTTC",
    image: "/nftmall.jpeg",
    categories: [categories.NFT,categories.HACKATHON],
  },
  {
    title: "Picasarts.io",
    url: "https://tron.picasarts.io/",
    description: "The Defi NFT Marketplace on TRON to mint, sell, buy NFTs and Loan, Lending Borrowing, Staking, Loyalty Program for NFTs",
    image: "/picasarts.Jpg",
    categories: [categories.NFT,categories.DEFI],
  },
  {
    title: "Station Bids",
    url: "https://stationbids.com/",
    description: "Fully decentralized NFT auction house on TRON",
    image: "/station-bids.png",
    categories: [categories.NFT,categories.HACKATHON],
  },
  {
    title: "Swap Station",
    url: "https://www.swapstation.io/preview",
    description: "Swap Station is a one of a kind marketplace for NFT collectors to showcase, discover, and swap NFTs across different blockchains. So instead of selling NFTs for crypto, you swap them!",
    image: "/swap-station.png",
    categories: [categories.NFT,categories.HACKATHON],
  },
  {
    title: "JustMoney Pay",
    url: "http://pay.just.money/",
    description: "Encouraging the mass adoption of cryptocurrencies & their utilization as a day-to-day payment method by creating an online payment interface through which users may easily purchase goods and services",
    image: "/justmoney.jpg",
    categories: [categories.DEFI,categories.HACKATHON],
  },
  {
    title: "Deba's Wulf Pack",
    url: "https://kraftly.io/mintable/148/gallery?page=1",
    description: "DWP is the first decentralised e-book on TRON Blockchain! #Web3 . Owning a #DWP gives users ownership of an original NFT, the e-book, resell rights and cash back options in NoleCrafts !",
    image: "/deba.jpeg",
    categories: [categories.NFT,categories.HACKATHON],
  },
  {
    title: "ERP = e-Plus",
    url: "http://www.erpeplus.com/universidad/Videos/0101CotizacionesParte1.mp4",
    description: "e-Plus: Enterprise Resource Planning-Customer and supplier management-Business Processes-Logistics and Operations-Purchasing Management-SAT and Accounting-Production / Manufacturing",
    image: "/erp.jpg",
    categories: [categories.DEFI,categories.HACKATHON],
  },
  {
    title: "Tron Weekly Journal",
    url: "https://www.tronweekly.com/",
    description: "With the arrival of technologies such as blockchain, there has been a boom in use-case based apps. Keeping a track of all the updates in the industry is where TWJ comes in.",
    image: "/tron-journal.png",
    categories: [categories.INFRASTRUCTURE],
  },
  {
    title: "SaTT",
    url: "https://satt-token.com/",
    description: "SaTT is a web3 influencer platform that allows users to get paid for a tweet, post, and video in a decentralized, permissionless, and blockchain-based environment.",
    image: "/satt.png",
    categories: [categories.HACKATHON],
  },
  {
    title: "Eagle Eye",
    url: "https://xd.adobe.com/view/52a7e95e-79c7-4b7e-b415-7ed817c627a2-07f4/screen/9910a440-422f-40aa-b8c5-0e5b7bb7e2b5?fullscreen&hints=off",
    description: "EAGLE EYE is a low-cost, easy-to-use platform for decentralized Web3/Crypto policing and DAO community with three variation of users:",
    image: "/eagle-eye.jpg",
    categories: [categories.HACKATHON],
  },
  {
    title: "Dbanta",
    url: "https://dbanta.netlify.app/",
    description: "A decentralised social media, you earn and also can Mint your post as NFTs",
    image: "/dbanta.png",
    categories: [categories.NFT,categories.HACKATHON],
  },
  {
    title: "Warp",
    url: "https://dex.ustx.io/warp.html",
    description: "Warp is a DeFi app, within the USTX ecosystem, that implements a pseudo delta neutral farming strategy. ",
    image: "/warp.jpg",
    categories: [categories.DEFI],
  },
  {
    title: "ThanX Finance",
    url: "https://thanx.finance/",
    description: "Building a multi-brand, crypto-based reward & loyalty platform. Users can earn up to 20% cryptoback in THANX tokens when they shop online, travel or book hotels via our extension or application.",
    image: "/thanx.png",
    categories: [categories.DEFI],
  },
  {
    title: "DIGITALMART",
    url: "http://digitalmartpolygon.netlify.app/",
    description: "DigitalMart is a decentralised marketplace which will provide users the ability to make purchases of whatever products of their needs, and also provide merchants a marketplace to market their products",
    image: "/digitalmart.png",
    categories: [categories.DEFI],
  },{
    title: "Carpe Diem Savings",
    url: "https://discord.gg/carpediem",
    description: "Carpe Diem’s Savings account is a decentralized Certificate of Deposit for any cryptocurrency. If a user claims their fully served stake, they will get back at least what they put in.",
    image: "/carpe-diem.png",
    categories: [categories.DEFI],
  },
  {
    title: "Crystl Finance",
    url: "https://www.crystl.finance/",
    description: "Crystl Finance is a Multi-chain Yield Aggregator. We offer novel Vaulting methods to DeFi/Blockchain projects & users to help maximize their liquidity and earnings & build the overall Ecosystem.",
    image: "/crystl-finance.png",
    categories: [categories.DEFI],
  },
  {
    title: "InterCrone World",
    url: "https://intercroneswap.com/",
    description: "Welcome to InterCrone! Join the coolest multichain swapping platform in the whole universe!",
    image: "/intercrone.png",
    categories: [categories.DEFI],
  },
  {
    title: "theRevolt",
    url: "http://therevolt.io/",
    description: "A completely new designed card-game that combines storytelling, gaming and decentralization - a milestone for the TRON community.",
    image: "/therevolt.png",
    categories: [categories.NFT],
  },
  {
    title: "Balrok",
    url: "https://balrok.io/",
    description: "Space shooting game with upgradable NFTs.",
    image: "/balrok.png",
    categories: [categories.DEFI],
  },
  {
    title: "Pet vs Pets - TRON",
    url: "https://subrays.com/play/",
    description: "Conquer the World of Pets!",
    image: "/pet.jpg",
    categories: [categories.DEFI,categories.NFT],
  },
  {
    title: "Moneyball",
    url: "https://testflight.apple.com/join/RQqRzMpF",
    description: "Play basketball, earn crypto.",
    image: "/moneyball.png",
    categories: [categories.NFT],
  },
  {
    title: "NFTBL | Your Own Football Team",
    url: "https://tron.kosyachniy.com/",
    description: "Web3 football game built around NFT players card collection. Gamers can manage their club, earn tokens, upgrade NFT's for them and battle in online P2P matches with each other",
    image: "/nftbl.gif",
    categories: [categories.NFT],
  },
  {
    title: "Africa Stars",
    url: "http://www.africastars.live/",
    description: "Africa Stars is the project where TuruGlobal reaches out the African continent to bring awarenes of the Role Africa has played and is playing in the global civilization and its culture.",
    image: "/africa-stars.png",
    categories: [categories.INFRASTRUCTURE],
  },
  {
    title: "Cubie",
    url: "https://dapp.cubie.art/",
    description: "CUBIE is a community-driven NFT GameFi platform empowering users by rewarding them for their engagement and enjoyment. By using creative NFTs, innovative tokenomics, utilizing finance and games.",
    image: "/cubie.jpg",
    categories: [categories.NFT],
  },
  {
    title: "Tronbies",
    url: "https://tronbies.io/",
    description: "We are presenting a way to bring forth value to the NFT circuit in Crypto relying not only on community but also on tech.",
    image: "/tronbies.jpg",
    categories: [categories.NFT],
  },
  {
    title: "Capitol Lion Music Network",
    url: "https://lionxeco.net/capitol-lion-genesis.html",
    description: "The Main Goal of Capitol Lion is to evolve The Traditional Music Scene. Ultimately creating a platform merging Products, Services, Tools and Resources of Music through the NFT Standard.",
    image: "/capitol-lion.png",
    categories: [categories.INFRASTRUCTURE],
  },
  {
    title: "T-Rex Punks",
    url: "https://github.com/Trex-punks/trex-punks",
    description: "T-Rex Punks the first Dino punk on the TRON blockchain!",
    image: "/t-rex.jpg",
    categories: [categories.DEFI],
  },
  {
    title: "JustRugNFT",
    url: "http://justrugnft.com/",
    description: "The first NFT launchpad on tron blockchain. Onboarding as much projects and collectors as possible and taking NFTs on tron to a whole new level.",
    image: "/justrug.jpg",
    categories: [categories.NFT],
  },
  {
    title: "Tokeniz",
    url: "https://generational.in/",
    description: "Mint NFTs while locking multiple tokens, and gift crypto in a interesting way, Allow Fee Less transactions on personal ecommerce platforms for selling crypto, and allow Trustless P2P transactions",
    image: "/tokeniz.png",
    categories: [categories.NFT],
  },
  {
    title: "Baoziswap",
    url: "https://baoziswap.com/",
    description: "Maintaining and Developing a Great and Sustainable Ecosystem on Tron Blockchain with Baoziswap Staking Pool",
    image: "/baoziswap.png",
    categories: [categories.DEFI],
  },
  {
    title: "Tokenomeme",
    url: "http://tokenomeme.wtf/",
    description: "The first multichain meme aggregator",
    image: "/tokenomeme.png",
    categories: [categories.DEFI],
  },
  {
    title: "Crypto Cannabis",
    url: "https://ccgdapp.com/",
    description: "Crypto Cannabis Grow is a seed to sale ledgering dapp built upon the Tron Blockchain. CCG DApp built back in 2018 is operational and available for licensed medical/recreational dispensaries use case.",
    image: "/crypto-cannabis.jpeg",
    categories: [categories.DEFI,categories.HACKATHON],
  },
  {
    title: "MeDo - Tron",
    url: "https://medo-tron-i5zty3n.spheron.app/",
    description: "MeDo - is a decentralized freelance platform where users can post paid tasks and other users can earn TRX by executing those tasks.",
    image: "/medo.jpg",
    categories: [categories.DEFI],
  },
  {
    title: "Nuclear Bridge",
    url: "https://shasta.tronscan.org/#/contract/TBJw14s8yB4qf2fYFJ6e3PxrbBij7mpYTR/code",
    description: "An innovative peer-to-peer trustless bridge based on atomic swaps.",
    image: "/nuclear-bridge.png",
    categories: [categories.DEFI],
  },
  {
    title: "African DeFi",
    url: "https://github.com/GETOfinance/Decentralised-Exchange",
    description: "Decentralised finance in African national currencies as stable coins with on-ramp and off-ramp on Desktop and Mobile serving the banked, underbanked and unbanked.",
    image: "/african-defi.jpeg",
    categories: [categories.DEFI],
  },
  {
    title: "TrūQoin DeFi Avalanche Staking",
    url: "https://truqoin.io/wallet-move",
    description: "TrūQoin at the close of each Block can be Staked in return for Activity Points, based on how many TrūQoin held in the Staking Wallet and multiplied by the Count-Multi and Stake-Multi.",
    image: "/truqoin.png",
    categories: [categories.DEFI],
  },
  {
    title: "2K",
    url: "https://github.com/tookey-io/monorep",
    description: "2K - blockchain security protocol designed to protect DeFi and Web3 platforms from private key disclosure threats, inducting distributed key management and signing system",
    image: "/2k.jpg",
    categories: [categories.DEFI],
  },
  {
    title: "VanSwap",
    url: "https://github.com/InfoVanswap/VanSwap-contratcts.git",
    description: "Vanswap is the leading DEX employed on Vision Network, with innovative `Token+NFT` model, building a place to trade, earn, invest and govern for users. Its cross-chain bridge support TRON network.",
    image: "/vanswap.jpeg",
    categories: [categories.DEFI],
  },
  {
    title: "Sifchain",
    url: "https://sifchain.network/",
    description: "Sifchain is a DEX built with the Cosmos SDK. We are building an interoperable Omni-EVM future where any asset from any blockchain can be moved freely and easily to any other blockchain.",
    image: "/sifchain.png",
    categories: [categories.DEFI],
  },
  {
    title: "Crypto Recycling Machine",
    url: "https://github.com/dzoni-hash/TRON-Grand-Hackathon-2022",
    description: "A dapp which brings together recycling and defi. Crypto Recycling Machine gives you an opportunity to recycle plastic, aluminium and glass bottles, and get paid in crypto.",
    image: "/recycling-machine.jpg",
    categories: [categories.DEFI],
  },
  {
    title: "LiquidaTHor for JustLend",
    url: "https://liquidathor.com/",
    description: "You can participate in DEFI liquidation. And you need for this just browser all LiquidaTHor will do others stuffs.",
    image: "/liquidathor.png",
    categories: [categories.DEFI],
  },
  {
    title: "Kōyō Finance",
    url: "https://koyo.finance/",
    description: "Kōyō Finance is a cross-chain DeFi exchange platform. It enables users to swap, deposit and withdraw their assets in one place, across multiple chains/networks.",
    image: "/koyo finance.png",
    categories: [categories.DEFI],
  },
  {
    title: "Match Systems",
    url: "https://matchsystems.com/",
    description: "Match Systems is a project specializing in implementation of compliance procedures for cryptocurrency projects (DeFi, Exchanges)",
    image: "/match.jpg",
    categories: [categories.DEFI],
  },
  {
    title: "JAFO Trading Club",
    url: "https://jafotradingclub.com/",
    description: "JAFO is a reward token. It is a club in the sense that your purchased funds are not used to trade with. Holding it gives you access to reward gains as a club member from a trade desk that is set up.",
    image: "/jafo.png",
    categories: [categories.DEFI],
  },
  {
    title: "AirCash",
    url: "https://aircash.finance/",
    description: "AirCash aims to be the best solution for crypto-fiat cash in and out.",
    image: "/aircash.jpeg",
    categories: [categories.DEFI],
  },
  {
    title: "Minimax Finance",
    url: "https://app.minimax.finance/",
    description: "We are building a dApp to enable people to conveniently manage all or most of their DeFi investments in one place. The dApp will provide unique features for safer and more profitable DeFi experience.",
    image: "/minimax.png",
    categories: [categories.DEFI],
  },
  {
    title: "Exonom",
    url: "https://github.com/KOSASIH/Exonom",
    description: "BEP20 & NFT ( BSC - Contract ). A next-generation Blockchain platform that uses patent pending technology to execute transactions via a state of the art secure, scalable, and green protocol. Exonom is geared towards enterprise applications, boasting a transaction rate that matches Visa in scale.",
    image: "/exonom.png",
    categories: [categories.DEFI],
  },
  {
    title: "Palm Finance",
    url: "http://54.254.5.72:8089/#/borrow",
    description: "More efficient yield acceleration solutions for new assets in Web3 Palm allows users to borrow up to 22x against their portfolio of NFTs, LP, interest-bearing tokens, or base assets at 0 interest.",
    image: "/palm-finance.png",
    categories: [categories.DEFI],
  },
  {
    title: "USDT Point of Sale",
    url: "https://play.google.com/store/apps/details?id=com.technoprepay.usdtpos",
    description: "ing USDT payments at your business. The TRON based USDT Point of Sale Application allows you to receive payments, add tips, print receipts and reports",
    image: "/usdt pos.png",
    categories: [categories.DEFI],
  },
  {
    title: "Trustified Work",
    url: "https://tn-tron.vercel.app/",
    description: "Trustified Work is a platform where DAOs, individuals, and businesses can Sell Digital Products/Services Globally and Accept Crypto Payments without paying Hefty Commissions.",
    image: "/trustified-work.png",
    categories: [categories.DEFI],
  },
  {
    title: "STKRS",
    url: "https://stkrs.me/#/",
    description: "Stkrs is the social identity app for Web 3.0. Users can express themselves, trust others online, and revolutionize our governance, all while being anon and maintaining privacy.",
    image: "/stkrs.jpeg",
    categories: [categories.DEFI],
  },
  {
    title: "Tron Wallet & Trading Bot",
    url: "https://github.com/barbarayler/TronWalletonAlexa",
    description: "Tron Wallet & Trading Bot on Alexa for the disabled, visually impaired and voice multitasking.",
    image: "/trading-bot.jpg",
    categories: [categories.DEFI],
  },
];